"""empty message

Revision ID: 5a38f32f9ac4
Revises: 9d891536720e
Create Date: 2022-05-27 15:01:27.690320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a38f32f9ac4'
down_revision = '9d891536720e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('image', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'image')
    # ### end Alembic commands ###
